### ISSUE TITLE
构建的镜像无法运行。

### ISSUE THREAD

**Issue by hmilylife** [jumpserver/Dockerfile#35]
通过官方的文件docker安装。启动不起来。 查看docker的日志如下。 
貌似是有个808端口的tomcat没启动起来。麻烦看看。

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8) 
9:C 09 May 15:38:35.485 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf 
                _._ 
           _.-``__ ''-._ 
      _.-``    `.  `_.  ''-._           Redis 3.2.12 (00000000/0) 64 bit 
  .-`` .-```.  ```\/    _.,_ ''-._ 
 (    '      ,       .-`  | `,    )     Running in standalone mode 
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379 
 |    `-._   `._    /     _.-'    |     PID: 9 
  `-._    `-._  `-./  _.-'    _.-' 
 |`-._`-._    `-.__.-'    _.-'_.-'| 
 |    `-._`-._        _.-'_.-'    |           http://redis.io 
  `-._    `-._`-.__.-'_.-'    _.-' 
 |`-._`-._    `-.__.-'    _.-'_.-'| 
 |    `-._`-._        _.-'_.-'    | 
  `-._    `-._`-.__.-'_.-'    _.-' 
      `-._    `-.__.-'    _.-' 
          `-._        _.-' 
              `-.__.-' 
 
9:M 09 May 15:38:35.543 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128. 
9:M 09 May 15:38:35.543 # Server started, Redis version 3.2.12 
9:M 09 May 15:38:35.544 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled. 
9:M 09 May 15:38:35.545 * The server is now ready to accept connections on port 6379 
190509 15:38:36 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'. 
Thu May  9 15:38:36 2019 
Jumpserver version 1.4.10, more see https://www.jumpserver.org 
 
- Start Gunicorn WSGI HTTP Server 
Check database connection ... 
190509 15:38:36 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql 
 
 [X] 0001_initial 
 [X] 0002_auto_20171225_1157 
 [X] 0003_auto_20180101_0046 
 [X] 0004_auto_20180125_1218 
 [X] 0005_auto_20180306_1804 
 [X] 0006_auto_20180411_1135 
 [X] 0007_auto_20180419_1036 
 [X] 0008_auto_20180425_1516 
 [X] 0009_auto_20180517_1537 
 [X] 0010_auto_20180606_1505 
 [X] 0011_user_source 
 [X] 0012_auto_20180710_1641 
 [X] 0013_auto_20180807_1116 
 [X] 0014_auto_20180816_1652 
 [X] 0015_auto_20181105_1112 
 [X] 0016_auto_20181109_1505 
 [X] 0017_auto_20181123_1113 
 [X] 0018_auto_20190107_1912 
 [X] 0019_auto_20190304_1459 
Database connect success 
Check database structure change ... 
Migrate model change to database ... 
 
admin, assets, audits, auth, authentication, captcha, common, contenttypes, django_celery_beat, ops, orgs, perms, sessions, settings, terminal, users 
 
  No migrations to apply. 
Collect static files 
 
552 static files copied to '/opt/jumpserver/data/static'. 
 
- Start Celery as Distributed Task Queue 
 
- Start Beat as Periodic Task Scheduler 
Error: celery start error 
Stop service: gunicorn 
celery is stopped 
beat is stopped 
Starting guacd: guacd[245]: INFO:	Guacamole proxy daemon (guacd) version 0.9.14 started 
SUCCESS 
Using CATALINA_BASE:   /config/tomcat8 
Using CATALINA_HOME:   /config/tomcat8 
Using CATALINA_TMPDIR: /config/tomcat8/temp 
Using JRE_HOME:        /usr 
Using CLASSPATH:       /config/tomcat8/bin/bootstrap.jar:/config/tomcat8/bin/tomcat-juli.jar 
Tomcat started. 
Use eventlet dispatch 
2019-05-09 15:39:56 [request ERROR] Connect endpoint http://127.0.0.1:8080 error: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/terminal/v2/terminal-registrations/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)) 
2019-05-09 15:39:56 [terminal ERROR] Connect endpoint http://127.0.0.1:8080 error: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/terminal/v2/terminal-registrations/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)) 
Traceback (most recent call last): 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn 
    (self.host, self.port), self.timeout, **extra_kw) 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection 
    raise err 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection 
    sock.connect(sa) 
  File "/opt/py3/lib64/python3.6/site-packages/eventlet/greenio/base.py", line 251, in connect 
    socket_checkerr(fd) 
  File "/opt/py3/lib64/python3.6/site-packages/eventlet/greenio/base.py", line 51, in socket_checkerr 
    raise socket.error(err, errno.errorcode[err]) 
ConnectionRefusedError: [Errno 111] ECONNREFUSED 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen 
    chunked=chunked) 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request 
    conn.request(method, url, **httplib_request_kw) 
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request 
    self._send_request(method, url, body, headers, encode_chunked) 
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request 
    self.endheaders(body, encode_chunked=encode_chunked) 
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders 
    self._send_output(message_body, encode_chunked=encode_chunked) 
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output 
    self.send(msg) 
  File "/usr/lib64/python3.6/http/client.py", line 964, in send 
    self.connect() 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 166, in connect 
    conn = self._new_conn() 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn 
    self, "Failed to establish a new connection: %s" % e) 
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/py3/lib64/python3.6/site-packages/requests/adapters.py", line 440, in send 
    timeout=timeout 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen 
    _stacktrace=sys.exc_info()[2]) 
  File "/opt/py3/lib64/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment 
    raise MaxRetryError(_pool, url, error or ResponseError(cause)) 
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/terminal/v2/terminal-registrations/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)) 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 115, in do 
    resp = req.do() 
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 53, in do 
    **self.kwargs 
  File "/opt/py3/lib64/python3.6/site-packages/requests/api.py", line 112, in post 
    return request('post', url, data=data, json=json, **kwargs) 
  File "/opt/py3/lib64/python3.6/site-packages/requests/api.py", line 58, in request 
    return session.request(method=method, url=url, **kwargs) 
  File "/opt/py3/lib64/python3.6/site-packages/requests/sessions.py", line 508, in request 
    resp = self.send(prep, **send_kwargs) 
  File "/opt/py3/lib64/python3.6/site-packages/requests/sessions.py", line 618, in send 
    r = adapter.send(request, **kwargs) 
  File "/opt/py3/lib64/python3.6/site-packages/requests/adapters.py", line 508, in send 
    raise ConnectionError(e, request=request) 
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/terminal/v2/terminal-registrations/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)) 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/opt/py3/lib64/python3.6/site-packages/jms/terminal.py", line 62, in register_terminal_v2 
    headers=headers 
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 129, in post 
    return self.do(*args, **kwargs) 
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 119, in do 
    raise RequestError(msg) 
jms.exception.RequestError: Connect endpoint http://127.0.0.1:8080 error: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/terminal/v2/terminal-registrations/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)) 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "./cocod", line 31, in <module> 
    from coco import Coco 
  File "/opt/coco/coco/__init__.py", line 6, in <module> 
    from .app import Coco 
  File "/opt/coco/coco/app.py", line 14, in <module> 
    from .sshd import SSHServer 
  File "/opt/coco/coco/sshd.py", line 13, in <module> 
    from coco.interface import SSHInterface 
  File "/opt/coco/coco/interface.py", line 11, in <module> 
    from .service import app_service 
  File "/opt/coco/coco/service.py", line 12, in <module> 
    app_service.initial() 
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 55, in initial 
    self.load_access_key() 
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 66, in load_access_key 
    self.register_and_save() 
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 93, in register_and_save 
    self.config['NAME'], self.config['BOOTSTRAP_TOKEN'] 
  File "/opt/py3/lib64/python3.6/site-packages/jms/terminal.py", line 67, in register_terminal_v2 
    raise RegisterError(msg) 
jms.exception.RegisterError: Connect endpoint http://127.0.0.1:8080 error: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/terminal/v2/terminal-registrations/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63464979e8>: Failed to establish a new connection: [Errno 111] ECONNREFUSED',)) 
Jumpserver ALL 1.4.10 
官网 http://www.jumpserver.org 
文档 http://docs.jumpserver.org 
有问题请参考 http://docs.jumpserver.org/zh/docs/faq.html 
 
进入容器命令 docker exec -it jms_all /bin/bash 
9:M 09 May 15:43:36.090 * 100 changes in 300 seconds. Saving... 
9:M 09 May 15:43:36.091 * Background saving started by pid 350 
350:C 09 May 15:43:36.101 * DB saved on disk 
350:C 09 May 15:43:36.102 * RDB: 0 MB of memory used by copy-on-write 
9:M 09 May 15:43:36.192 * Background saving terminated with success 
```

**Comment by wojiushixiaobai** [comment]
@hmilylife 原因是由于jumpserver应用启动失败，导致后面的coco也启动失败，检查硬件配置

**Comment by hmilylife** [comment]
jumpserver启动依赖什么特别的硬件配置吗 ？
