### ISSUE TITLE
Docker快速部署遇到Access denied for user 'root'@'172.17.0.2' (using password: YES)

### ISSUE THREAD

**Issue by OpsDarren** [jumpserver/Dockerfile#60]
请问docker快速部署，已经生成了SECRET_KEY和BOOTSTRAP_TOKEN，搭好Redis和MariaDB并按官方文档创建了jumpserver数据库，在运行docker命令
```
docker run --name jms_all -d \
-v /opt/jumpserver:/opt/jumpserver/data/media \
-p 80:80 \
-p 2222:2222 \
-e SECRET_KEY=mR48jsB3TS9uxDkYgpciJmRTDddcBetDBE8rGqtZX7B9xtrCMh \
-e BOOTSTRAP_TOKEN=0s8NLn8RJlCkcRf9 \
-e DB_HOST=10.10.10.22 \  //我的测试环境IP
-e DB_PORT=3306 \
-e DB_USER=root \
-e DB_PASSWORD=Server \  //MySQL密码确定没错
-e DB_NAME=jumpserver \
-e REDIS_HOST=10.10.10.22 \
-e REDIS_PORT=6379 \
-e REDIS_PASSWORD=Jump \  //Redis密码确定没错
jumpserver/jms_all:1.5.7  //1.5.7和latest版本都试过
```
出现以下错误，
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 48, in handle
    return self.show_list(connection, options['app_label'])
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 67, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2006, "Access denied for user 'root'@'172.17.0.2' (using password: YES)")
2020-05-12 22:30:03 Check database connection ...
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2006, "Access denied for user 'root'@'172.17.0.2' (using password: YES)")
2020-05-12 22:31:40 Connection database failed, exist

- Start Gunicorn WSGI HTTP Server
guacd[404]: INFO:       Guacamole proxy daemon (guacd) version 1.0.0 started
Starting guacd: SUCCESS
Tomcat started.
Jumpserver ALL 
官网 http://www.jumpserver.org
文档 http://docs.jumpserver.org
有问题请参考 http://docs.jumpserver.org/zh/docs/faq.html

进入容器命令 docker exec -it jms_all /bin/bash
```
请问这个172.17.0.2是什么IP，这个错误需要怎么解决？

**Comment by wojiushixiaobai** [comment]
@OpsDarren mysql授权用户授权给宿主ip，或者直接用root@%
如果不清楚我在说什么，请使用内置数据库和redis

**Comment by OpsDarren** [comment]
> @OpsDarren mysql授权用户授权给宿主ip，或者直接用root@%
> 如果不清楚我在说什么，请使用内置数据库和redis

谢谢您，我想我应该理解了您的意思，因为我部署MySQL的时候使用的是root用户，但是我直接使用官方文档提供的创建数据库命令
```
create database jumpserver default charset 'utf8' collate 'utf8_bin';
grant all on jumpserver.* to 'jumpserver'@'%' identified by 'weakPassword';  //您说的应该就是这里我其实应该输入'root'@'%'才对吧，by后面是我的MySQL密码，这个我知道
```

**Comment by OpsDarren** [comment]
回家测试后问题已解决，多谢解答，确实是这个问题
