### ISSUE TITLE
docker 安装到最后--报redis错误

### ISSUE THREAD

**Issue by sunfuzhou** [jumpserver/Dockerfile#91]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
2. 
3. Deleting 'admin/js/vendor/xregexp/xregexp.min.js'

477 static files copied to '/opt/jumpserver/data/static'.
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 91, in delete
    return self.client.delete(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/client/default.py", line 246, in delete
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 99 connecting to None:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/jumpserver/apps/common/management/commands/expire_caches.py", line 27, in handle
    expire_node_assets_mapping()
  File "/opt/jumpserver/apps/common/management/commands/expire_caches.py", line 13, in expire_node_assets_mapping
    expire_node_assets_mapping_for_memory(org_id)
  File "/opt/jumpserver/apps/assets/signals_handler/node_assets_mapping.py", line 47, in expire_node_assets_mapping_for_memory
    Node.expire_node_all_asset_ids_mapping_from_cache(org_id)
  File "/opt/jumpserver/apps/assets/models/node.py", line 355, in expire_node_all_asset_ids_mapping_from_cache
    cache.delete(cache_key)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/opt/py3/lib/python3.8/site-packages/django_redis/client/default.py", line 243, in delete
    return client.delete(self.make_key(key, version=version,
  File "/opt/py3/lib/python3.8/site-packages/redis/client.py", line 1567, in delete
    return self.execute_command('DEL', *names)
  File "/opt/py3/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/py3/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to None:6379. Cannot assign requested address.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/client/default.py", line 145, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 99 connecting to None:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/terminal/startup.py", line 55, in start_heartbeat
    status_serializer.save()
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/opt/py3/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/jumpserver/apps/terminal/models/status.py", line 62, in save
    self.terminal.set_alive(ttl=120)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 56, in set_alive
    cache.set(key, True, ttl)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/opt/py3/lib/python3.8/site-packages/django_redis/client/default.py", line 139, in set
    return bool(client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx))
  File "/opt/py3/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/opt/py3/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/py3/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to None:6379. Cannot assign requested address.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/client/default.py", line 145, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 99 connecting to None:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/terminal/startup.py", line 55, in start_heartbeat
    status_serializer.save()
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/opt/py3/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/jumpserver/apps/terminal/models/status.py", line 62, in save
    self.terminal.set_alive(ttl=120)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 56, in set_alive
    cache.set(key, True, ttl)
  File "/opt/py3/lib/python3.8/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/opt/py3/lib/python3.8/site-packages/django_redis/client/default.py", line 139, in set
    return bool(client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx))
  File "/opt/py3/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/opt/py3/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/py3/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to None:6379. Cannot assign requested address.
Starting supervisor: supervisord.
Jumpserver ALL v2.15.3
官网 http://www.jumpserver.org
文档 http://docs.jumpserver.org

进入容器命令 docker exec -it jms_all /bin/bash

**Comment by wojiushixiaobai** [comment]
提示很明确，Error 99 connecting to None:6379.
None是你的主机？
